/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ReviewImage from 'assets/images/homePage/Group48__review.png';
import { styled } from '@mui/material/styles';
import Component1 from 'ui-component/homePage/Component1';

const Group481 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `370px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Section = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  height: `370px`,
  left: `0px`,
  top: `0px`,

});

const Group47 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1028.33px`,
  height: `370px`,
  margin: `0px`,
  widht:'100%',
});

const Left = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `485px`,
  left: `0px`,
  top: `0px`,
});

const TitleDescription = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const NosTemoignages = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontWeight: `700`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `72px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const DecouvrezNosDifferen = styled('div')(() => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(93, 95, 239, 1)`,
  fontStyle: `normal`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `29px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `16px 0px 0px 0px`,
}));

const Right = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `505px`,
  top: `0px`,
});

const Review = styled('img')({
  height: `207px`,
  width: `373.33px`,
  margin: `0px`,
});

const Component11 = styled(Component1)(() => ({
  height: `52px`,
  width: `523px`,
  margin: `24px 0px 0px 0px`,
}));

function CardTemoignages(props) {
  return (
    <Group481 className={props.className}>
      <Section>
        <Group47>
          <Left>
            <TitleDescription>
              <NosTemoignages>{`Nos Temoignages`}</NosTemoignages>
              <DecouvrezNosDifferen>
                {`Decouvrez nos differentes fonctionnalites`}
              </DecouvrezNosDifferen>
            </TitleDescription>
          </Left>
          <Right>
            <Review src={ReviewImage} loading="lazy" alt={'_review'} />
            <Component11 />
          </Right>
        </Group47>
      </Section>
    </Group481>
  );
}

export default CardTemoignages;
