/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Ellipse1Image from 'assets/images/homePage/Component1_Ellipse_1.png';
import Ellipse2Image from 'assets/images/homePage/Component1_Ellipse_2.png';
import Polygon1Image from 'assets/images/homePage/Component1_Polygon_1.png';
import { styled } from '@mui/material/styles';

const Component11 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `52px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Objectif = styled('div')(() => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(162, 158, 188, 1)`,
  fontStyle: `normal`,
  fontFamily: `Mulish`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `410px`,
  top: `1px`,
}));

const Rectangle8 = styled('div')({
  backgroundColor: `rgba(199, 211, 235, 1)`,
  borderRadius: `10px`,
  width: `392px`,
  height: `10px`,
  position: `absolute`,
  left: `0px`,
  top: `37px`,
});

const Rectangle7 = styled('div')({
  backgroundColor: `rgba(71, 178, 255, 1)`,
  borderRadius: `10px`,
  width: `198px`,
  height: `10px`,
  position: `absolute`,
  left: `0px`,
  top: `37px`,
});

const Circle = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `20px`,
  height: `20px`,
  left: `186px`,
  top: `32px`,
});

const Ellipse1 = styled('img')({
  height: `20px`,
  width: `20px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Ellipse2 = styled('img')({
  height: `12px`,
  width: `12px`,
  position: `absolute`,
  left: `4px`,
  top: `4px`,
});

const TextBg = styled('div')({
  backgroundColor: `rgba(49, 116, 165, 1)`,
  borderRadius: `4px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `4px`,
  boxSizing: `border-box`,
  left: `176px`,
  top: `0px`,
});

const Text = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Q50 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `600`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Polygon1 = styled('img')({
  height: `10px`,
  width: `10px`,
  position: `absolute`,
  left: `32px`,
  top: `39px`,
});

const Q500 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `109px`,
  height: `25px`,
  position: `absolute`,
  left: `414px`,
  top: `27px`,
});

function Component1(props) {
  return (
    <Component11 className={props.className}>
      <Objectif>{`Objectif : `}</Objectif>
      <Rectangle8></Rectangle8>
      <Rectangle7></Rectangle7>
      <Circle>
        <Ellipse1 src={Ellipse1Image} loading="lazy" alt={'Ellipse 1'} />
        <Ellipse2 src={Ellipse2Image} loading="lazy" alt={'Ellipse 2'} />
      </Circle>
      <TextBg>
        <Text>
          <Q50>{`50%`}</Q50>
        </Text>
        <Polygon1 src={Polygon1Image} loading="lazy" alt={'Polygon 1'} />
      </TextBg>
      <Q500>{`500€`}</Q500>
    </Component11>
  );
}

export default Component1;
