/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import VectorImage from 'assets/images/homePage/Section_Vector.png';
import Vector1Image from 'assets/images/homePage/Section_Vector_1.png';
import Vector2Image from 'assets/images/homePage/Section_Vector_2.png';
import Vector3Image from 'assets/images/homePage/Section_Vector_3.png';
import Vector4Image from 'assets/images/homePage/Section_Vector_4.png';
import Vector5Image from 'assets/images/homePage/Section_Vector_5.png';
import Vector6Image from 'assets/images/homePage/Section_Vector_6.png';
import { styled } from '@mui/material/styles';

const Section1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const Left = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `485px`,
  margin: `0px`,
});

const TitleDescription = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const NosFonctionnalites = styled('div')(() => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(67, 62, 91, 1)`,
  fontStyle: `normal`,
  fontWeight: `700`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `72px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
}));

const DecouvrezNosDifferen = styled('div')(() => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(58, 73, 99, 1)`,
  fontStyle: `normal`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `29px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `16px 0px 0px 0px`,
}));

const Right = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Row1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Card1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `16px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `24px`,
  boxSizing: `border-box`,
  width: `276px`,
  margin: `0px`,
});

const Content = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `222px`,
  margin: `0px`,
});

const IconAndTitle = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const WorkOutline = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector = styled('img')({
  height: `22px`,
  width: `24px`,
  position: `absolute`,
  left: `0px`,
  top: `1px`,
});

const SuiviDesDepenses = styled('div')(() => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(40, 64, 125, 1)`,
  fontStyle: `normal`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 8px`,
}));

const LoremIpsumDolorSitAm = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `16px 0px 0px 0px`,
});

const Card2 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `16px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `24px`,
  boxSizing: `border-box`,
  width: `276px`,
  margin: `0px 0px 0px 24px`,
});

const Content1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `222px`,
  margin: `0px`,
});

const IconAndTitle1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const AddLocationAlt = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector1 = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector2 = styled('img')({
  height: `22px`,
  width: `19px`,
  position: `absolute`,
  left: `4px`,
  top: `1px`,
});

const BudgetPersonnalise = styled('div')(() => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(40, 64, 125, 1)`,
  fontStyle: `normal`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 8px`,
}));

const LoremIpsumDolorSitAm1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `16px 0px 0px 0px`,
});

const Row2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `24px 0px 0px 0px`,
});

const Card3 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `16px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `24px`,
  boxSizing: `border-box`,
  width: `276px`,
  margin: `0px`,
});

const Content2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `222px`,
  margin: `0px`,
});

const IconAndTitle2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const GTranslate = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector3 = styled('img')({
  height: `22px`,
  width: `22px`,
  position: `absolute`,
  left: `1px`,
  top: `1px`,
});

const Vector4 = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Previsions = styled('div')(() => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(40, 64, 125, 1)`,
  fontStyle: `normal`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 8px`,
}));

const LoremIpsumDolorSitAm2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `16px 0px 0px 0px`,
});

const Card4 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `16px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `24px`,
  boxSizing: `border-box`,
  width: `276px`,
  margin: `0px 0px 0px 24px`,
});

const Content3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `222px`,
  margin: `0px`,
});

const IconAndTitle3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const StackedBarChart = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector5 = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector6 = styled('img')({
  height: `15px`,
  width: `13px`,
  position: `absolute`,
  left: `6px`,
  top: `5px`,
});

const AlertesEtRappels = styled('div')(() => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(40, 64, 125, 1)`,
  fontStyle: `normal`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 8px`,
}));

const LoremIpsumDolorSitAm3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `16px 0px 0px 0px`,
});

function Section(props) {
  return (
    <Section1 className={props.className}>
      <Left>
        <TitleDescription>
          <NosFonctionnalites>{`Nos Fonctionnalites`}</NosFonctionnalites>
          <DecouvrezNosDifferen>
            {`Decouvrez nos differentes fonctionnalités`}
          </DecouvrezNosDifferen>
        </TitleDescription>
      </Left>
      <Right>
        <Row1>
          <Card1>
            <Content>
              <IconAndTitle>
                <WorkOutline>
                  <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
                </WorkOutline>
                <SuiviDesDepenses>{`Suivi des depenses`}</SuiviDesDepenses>
              </IconAndTitle>
              <LoremIpsumDolorSitAm>
                {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enim nisl.`}
              </LoremIpsumDolorSitAm>
            </Content>
          </Card1>
          <Card2>
            <Content1>
              <IconAndTitle1>
                <AddLocationAlt>
                  <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
                  <Vector2 src={Vector2Image} loading="lazy" alt={'Vector'} />
                </AddLocationAlt>
                <BudgetPersonnalise>{`Budget personnalise`}</BudgetPersonnalise>
              </IconAndTitle1>
              <LoremIpsumDolorSitAm1>
                {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enim nisl.`}
              </LoremIpsumDolorSitAm1>
            </Content1>
          </Card2>
        </Row1>
        <Row2>
          <Card3>
            <Content2>
              <IconAndTitle2>
                <GTranslate>
                  <Vector3 src={Vector3Image} loading="lazy" alt={'Vector'} />
                  <Vector4 src={Vector4Image} loading="lazy" alt={'Vector'} />
                </GTranslate>
                <Previsions>{`Previsions `}</Previsions>
              </IconAndTitle2>
              <LoremIpsumDolorSitAm2>
                {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enim nisl.`}
              </LoremIpsumDolorSitAm2>
            </Content2>
          </Card3>
          <Card4>
            <Content3>
              <IconAndTitle3>
                <StackedBarChart>
                  <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
                  <Vector6 src={Vector6Image} loading="lazy" alt={'Vector'} />
                </StackedBarChart>
                <AlertesEtRappels>{`Alertes et rappels`}</AlertesEtRappels>
              </IconAndTitle3>
              <LoremIpsumDolorSitAm3>
                {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enim nisl.`}
              </LoremIpsumDolorSitAm3>
            </Content3>
          </Card4>
        </Row2>
      </Right>
    </Section1>
  );
}

export default Section;
