apiVersion: v1
kind: Service
metadata:
  namespace: challenge-service
  name: challenge-gateway-service
spec:
  selector:
    gateway: challenge-gateway-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name : challenge-gateway-service
  namespace: challenge-service
  labels:
    gateway: challenge-gateway-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      gateway: challenge-gateway-service
  template:
    metadata:
      labels:
        gateway: challenge-gateway-service
    spec:
      containers:
      - name: challenge-gateway-service
        image: ronantr/challenge-gateway-service:latest

        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: challenge-service
  name: challenge-alerts-service
spec:
  selector:
    alerts: challenge-alerts-service
  ports:
    - protocol: TCP
      port: 3006
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name : challenge-alerts-service
  namespace: challenge-service
  labels:
    alerts: challenge-alerts-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      alerts: challenge-alerts-service
  template:
    metadata:
      labels:
        alerts: challenge-alerts-service
    spec:
      containers:
      - name: challenge-alerts-service
        image: ronantr/challenge-alerts-service:latest

        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3006
        readinessProbe:
          tcpSocket:
            port: 3006
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  namespace: challenge-service
  name: challenge-budgets-service
spec:
  selector:
    budgets: challenge-budgets-service
  ports:
    - protocol: TCP
      port: 3005
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name : challenge-budgets-service
  namespace: challenge-service
  labels:
    budgets: challenge-budgets-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      budgets: challenge-budgets-service
  template:
    metadata:
      labels:
        budgets: challenge-budgets-service
    spec:
      containers:
      - name: challenge-budgets-service
        image: ronantr/challenge-budgets-service:latest

        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3005
        readinessProbe:
          tcpSocket:
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  namespace: challenge-service
  name: challenge-debts-service
spec:
  selector:
    debts: challenge-debts-service
  ports:
    - protocol: TCP
      port: 3008
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name : challenge-debts-service
  namespace: challenge-service
  labels:
    debts: challenge-debts-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      debts: challenge-debts-service
  template:
    metadata:
      labels:
        debts: challenge-debts-service
    spec:
      containers:
      - name: challenge-debts-service
        image: ronantr/challenge-debts-service:latest

        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3008
        readinessProbe:
          tcpSocket:
            port: 3008
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  namespace: challenge-service
  name: challenge-events-service
spec:
  selector:
    events: challenge-events-service
  ports:
    - protocol: TCP
      port: 3009
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name : challenge-events-service
  namespace: challenge-service
  labels:
    events: challenge-events-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      events: challenge-events-service
  template:
    metadata:
      labels:
        events: challenge-events-service
    spec:
      containers:
      - name: challenge-events-service
        image: ronantr/challenge-events-service:latest

        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3009
        readinessProbe:
          tcpSocket:
            port: 3009
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  namespace: challenge-service
  name: challenge-expenses-service
spec:
  selector:
    expenses: challenge-expenses-service
  ports:
    - protocol: TCP
      port: 3004
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name : challenge-expenses-service
  namespace: challenge-service
  labels:
    expenses: challenge-expenses-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      expenses: challenge-expenses-service
  template:
    metadata:
      labels:
        expenses: challenge-expenses-service
    spec:
      containers:
      - name: challenge-expenses-service
        image: ronantr/challenge-expenses-service:latest

        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3004
        readinessProbe:
          tcpSocket:
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  namespace: challenge-service
  name: challenge-incomes-service
spec:
  selector:
    incomes: challenge-incomes-service
  ports:
    - protocol: TCP
      port: 3010
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name : challenge-incomes-service
  namespace: challenge-service
  labels:
    incomes: challenge-incomes-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      incomes: challenge-incomes-service
  template:
    metadata:
      labels:
        incomes: challenge-incomes-service
    spec:
      containers:
      - name: challenge-incomes-service
        image: ronantr/challenge-incomes-service:latest

        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3010
        readinessProbe:
          tcpSocket:
            port: 3010
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: challenge-service
  name: challenge-users-service
spec:
  selector:
    users: challenge-users-service
  ports:
    - protocol: TCP
      port: 3002
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name : challenge-users-service
  namespace: challenge-service
  labels:
    users: challenge-users-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      users: challenge-users-service
  template:
    metadata:
      labels:
        users: challenge-users-service
    spec:
      containers:
      - name: challenge-users-service
        image: ronantr/challenge-users-service:latest

        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3002
        readinessProbe:
          tcpSocket:
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: challenge-service
  name: challenge-categories-service
spec:
  selector:
    categories: challenge-categories-service
  ports:
    - protocol: TCP
      port: 3007
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name : challenge-categories-service
  namespace: challenge-service
  labels:
    categories: challenge-categories-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      categories: challenge-categories-service
  template:
    metadata:
      labels:
        categories: challenge-categories-service
    spec:
      containers:
      - name: challenge-categories-service
        image: ronantr/challenge-categories-service:latest

        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3007
        readinessProbe:
          tcpSocket:
            port: 3007
          initialDelaySeconds: 5
          periodSeconds: 5