version: "3"

services:
  challenge-gateway-service:
    image: ronantr/challange-gateway-service:0.2.0 
    ports:
      - 3000:3000
    deploy:
      replicas: 5

  challenge-alerts-service:
    image: ronantr/challenge-alerts-service:0.2.0
    environment:
      DATABASE_NAME: &challengeDatabaseName challenge
      DATABASE_USER: &challengeDatabaseUser challengeuser
      DATABASE_PASSWORD: &challengeDatabasePassword challengepass
    deploy:
      replicas: 5

  challenge-budgets-service:
    image: ronantr/challenge-budgets-service:0.2.0
    environment:
      DATABASE_NAME: &challengeDatabaseName challenge
      DATABASE_USER: &challengeDatabaseUser challengeuser
      DATABASE_PASSWORD: &challengeDatabasePassword challengepass
    deploy:
      replicas: 5

  challenge-debts-service:
    image: ronantr/challenge-debts-service:0.2.0
    environment:
      DATABASE_NAME: &challengeDatabaseName challenge
      DATABASE_USER: &challengeDatabaseUser challengeuser
      DATABASE_PASSWORD: &challengeDatabasePassword challengepass
    deploy:
      replicas: 5

  challenge-events-service:
    image: ronantr/challenge-events-service:0.2.0
    environment:
      DATABASE_NAME: &challengeDatabaseName challenge
      DATABASE_USER: &challengeDatabaseUser challengeuser
      DATABASE_PASSWORD: &challengeDatabasePassword challengepass
    deploy:
      replicas: 5

  challenge-expenses-service:
    image: ronantr/challenge-expenses-service:0.2.0
    environment:
      DATABASE_NAME: &challengeDatabaseName challenge
      DATABASE_USER: &challengeDatabaseUser challengeuser
      DATABASE_PASSWORD: &challengeDatabasePassword challengepass
    deploy:
      replicas: 5

  challenge-incomes-service:
    image: ronantr/challenge-incomes-service:0.2.0
    environment:
      DATABASE_NAME: &challengeDatabaseName challenge
      DATABASE_USER: &challengeDatabaseUser challengeuser
      DATABASE_PASSWORD: &challengeDatabasePassword challengepass
    deploy:
      replicas: 5

  challenge-users-service:
    image: ronantr/challenge-users-service:0.2.0
    environment:
      DATABASE_NAME: &challengeDatabaseName challenge
      DATABASE_USER: &challengeDatabaseUser challengeuser
      DATABASE_PASSWORD: &challengeDatabasePassword challengepass
    deploy:
      replicas: 5

  challenge-categories-service:
    image: ronantr/challenge-categoryes-service:0.2.0
    environment:
      DATABASE_NAME: &challengeDatabaseName challenge
      DATABASE_USER: &challengeDatabaseUser challengeuser
      DATABASE_PASSWORD: &challengeDatabasePassword challengepass
    deploy:
      replicas: 5

  challenge-database:
    image: ronantr/challenge-database:0.1.2
    environment:
      POSTGRES_DB: *challengeDatabaseName
      POSTGRES_USER: *challengeDatabaseUser
      POSTGRES_PASSWORD: *challengeDatabasePassword
    deploy:
      replicas: 1
