version: "3"

services:
  challenge-gateway-service:
    build:
      context: services/gateway
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./services/gateway:/home/node

  challenge-alerts-service:
    build:
      context: services/alerts
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/alerts:/home/node
    environment:
      POSTGRES_DB: &challengeDatabaseName challenge
      POSTGRES_USER: &challengeDatabaseUser challengeuser
      POSTGRES_PASSWORD: &challengeDatabasePassword challengepass

  challenge-categories-service:
    build:
      context: services/categories
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/alerts:/home/node
    environment:
      POSTGRES_DB: &challengeDatabaseName challenge
      POSTGRES_USER: &challengeDatabaseUser challengeuser
      POSTGRES_PASSWORD: &challengeDatabasePassword challengepass

  challenge-events-service:
    build:
      context: services/events
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/events:/home/node
    environment:
      POSTGRES_DB: &challengeDatabaseName challenge
      POSTGRES_USER: &challengeDatabaseUser challengeuser
      POSTGRES_PASSWORD: &challengeDatabasePassword challengepass

  challenge-debts-service:
    build:
      context: services/debts
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/debts:/home/node
    environment:
      POSTGRES_DB: *challengeDatabaseName 
      POSTGRES_USER: *challengeDatabaseUser 
      POSTGRES_PASSWORD: *challengeDatabasePassword 

  challenge-budgets-service:
    build:
      context: services/budgets
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/budgets:/home/node
    environment:
      POSTGRES_DB: *challengeDatabaseName 
      POSTGRES_USER: *challengeDatabaseUser 
      POSTGRES_PASSWORD: *challengeDatabasePassword 

  challenge-expenses-service:
    build:
      context: services/expenses
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/expenses:/home/node
    environment:
      POSTGRES_DB: *challengeDatabaseName 
      POSTGRES_USER: *challengeDatabaseUser 
      POSTGRES_PASSWORD: *challengeDatabasePassword

  challenge-incomes-service:
    build:
      context: services/incomes
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/incomes:/home/node
    environment:
      POSTGRES_DB: *challengeDatabaseName 
      POSTGRES_USER: *challengeDatabaseUser 
      POSTGRES_PASSWORD: *challengeDatabasePassword 

  challenge-users-service:
    build:
      context: services/users
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/users:/home/node
    environment:
      POSTGRES_DB: *challengeDatabaseName 
      POSTGRES_USER: *challengeDatabaseUser 
      POSTGRES_PASSWORD: *challengeDatabasePassword
      
    depends_on:
      - challenge-database

  challenge-database:
    build:
      context: services/database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: *challengeDatabaseName
      POSTGRES_USER: *challengeDatabaseUser
      POSTGRES_PASSWORD: *challengeDatabasePassword

  posts-service:
    build:
      context: services/posts
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/posts:/home/node
    environment:
      POSTGRES_DB: *challengeDatabaseName 
      POSTGRES_USER: *challengeDatabaseUser 
      POSTGRES_PASSWORD: *challengeDatabasePassword 

  adminer:
      image: adminer:latest
      ports:
        - 8080:8080
      environment:
        - ADMINER_DESIGN=dracula
      depends_on:
        - challenge-database