version: '3'
services:
  task:
    build: ./task
    restart: always
    hostname: task
    env_file:
      - .env.test
    networks:
      - backend
    links:
      - db
    ports:
      - ${TASK_SERVICE_PORT}:${TASK_SERVICE_PORT}
  token:
    build: ./token
    restart: always
    hostname: token
    env_file:
      - .env.test
    networks:
      - backend
    links:
      - db
    ports:
      - ${TOKEN_SERVICE_PORT}:${TOKEN_SERVICE_PORT}
  mailer:
    build: ./mailer
    restart: always
    hostname: mailer
    env_file:
      - .env.test
    networks:
      - backend
    ports:
      - ${MAILER_SERVICE_PORT}:${MAILER_SERVICE_PORT}
  permission:
    build: ./permission
    restart: always
    hostname: permission
    env_file:
      - .env.test
    networks:
      - backend
    ports:
      - ${PERMISSION_SERVICE_PORT}:${PERMISSION_SERVICE_PORT}
  user:
    build: ./user
    restart: always
    hostname: user
    env_file:
      - .env.test
    networks:
      - backend
    links:
      - mailer
      - db
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
  db:
    image: postgres:14
    container_name: postgres
    networks:
      - backend
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - 5432:5432

networks:
  backend:
    driver: bridge
