export default [
    {
        id: 1,
        incomeName: 'Salaire',
        amountEarned: 2000,
        dateEarned: '2023/06/18',
        description: 'Revenu mensuel',
    },
    {
        id: 2,
        incomeName: 'Freelance',
        amountEarned: 500,
        dateEarned: '2023/06/17',
        description: 'Projet de design',
    },
    {
        id: 3,
        incomeName: 'Location',
        amountEarned: 700,
        dateEarned: '2023/06/15',
        description: 'Revenu locatif',
    },
    {
        id: 4,
        incomeName: 'Vente en ligne',
        amountEarned: 300,
        dateEarned: '2023/06/14',
        description: 'Vente de produits sur une plateforme en ligne',
    },
    {
        id: 5,
        incomeName: 'Investissements',
        amountEarned: 1000,
        dateEarned: '2023/06/12',
        description: 'Revenu de dividendes',
    },
    {
        id: 6,
        incomeName: 'Consulting',
        amountEarned: 400,
        dateEarned: '2023/06/10',
        description: 'Consultation pour une entreprise',
    },
    {
        id: 7,
        incomeName: 'Bourse',
        amountEarned: 600,
        dateEarned: '2023/06/08',
        description: 'Revenu de trading',
    },
    {
        id: 8,
        incomeName: 'YouTube',
        amountEarned: 200,
        dateEarned: '2023/06/05',
        description: 'Revenu publicitaire sur YouTube',
    },
    {
        id: 9,
        incomeName: 'Cours en ligne',
        amountEarned: 350,
        dateEarned: '2023/06/03',
        description: 'Vente de cours en ligne',
    },
    {
        id: 10,
        incomeName: 'Photographie',
        amountEarned: 250,
        dateEarned: '2023/06/01',
        description: 'Revenu de séances photo',
    },
];
