version: "3"

services:
  challange-gateway-service:
    build:
      context: services/gateway
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./services/gateway:/home/node

  challenge-alerts-service:
    build:
      context: services/alerts
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/alerts:/home/node
    environment:
      DATABASE_NAME: &challangeDatabaseName challange
      DATABASE_USER: &challangeDatabaseUser challangeuser
      DATABASE_PASSWORD: &challangeDatabasePassword challangepass

  challenge-categorys-service:
    build:
      context: services/categorys
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/alerts:/home/node
    environment:
      POSTGRES_DB: *challangeDatabaseName
      POSTGRES_USER: *challangeDatabaseUser
      POSTGRES_PASSWORD: *challangeDatabasePassword

  challenge-events-service:
    build:
      context: services/events
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/events:/home/node
    environment:
      POSTGRES_DB: *challangeDatabaseName
      POSTGRES_USER: *challangeDatabaseUser
      POSTGRES_PASSWORD: *challangeDatabasePassword

  challenge-debts-service:
    build:
      context: services/debts
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/debts:/home/node
    environment:
      POSTGRES_DB: *challangeDatabaseName
      POSTGRES_USER: *challangeDatabaseUser
      POSTGRES_PASSWORD: *challangeDatabasePassword

  challenge-expenses-service:
    build:
      context: services/expenses
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/expenses:/home/node
    environment:
      POSTGRES_DB: *challangeDatabaseName
      POSTGRES_USER: *challangeDatabaseUser
      POSTGRES_PASSWORD: *challangeDatabasePassword

  challenge-incomes-service:
    build:
      context: services/incomes
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/incomes:/home/node
    environment:
      POSTGRES_DB: *challangeDatabaseName
      POSTGRES_USER: *challangeDatabaseUser
      POSTGRES_PASSWORD: *challangeDatabasePassword

  challenge-users-service:
    build:
      context: services/users
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/users:/home/node
    environment:
      POSTGRES_DB: *challangeDatabaseName
      POSTGRES_USER: *challangeDatabaseUser
      POSTGRES_PASSWORD: *challangeDatabasePassword

  challange-database:
    build:
      context: services/database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: *challangeDatabaseName
      POSTGRES_USER: *challangeDatabaseUser
      POSTGRES_PASSWORD: *challangeDatabasePassword

  posts-service:
    build:
      context: services/posts
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ./services/posts:/home/node
    environment:
      POSTGRES_DB: *challangeDatabaseName
      POSTGRES_USER: *challangeDatabaseUser
      POSTGRES_PASSWORD: *challangeDatabasePassword